import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import HeaderWebsite from "@/components/website/header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/website/AppSidebar";

const robotoSans = Inter({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: "500",
});

const spaceMono = Roboto({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoSans.className} ${spaceMono.className} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="container px-4 xl:px-0">
            {/* ----- Header Section ----- */}
            <section>
              <HeaderWebsite />
            </section>
            {/* ----- End Header Section----- */}
            {/* ----- Content Section----- */}
            {/* <section>{children}</section> */}
            {/* ----- End Content Section----- */}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}

// Author : M. Hamdan Yusuf 😎
